[sinks.console_sink]
type = "console"
inputs = [ "cubejs-server", "redis", "demo-logs" ]
[sinks.console_sink.encoding]
codec = "json"

[sinks.console_sink_cubestore]
type = "console"
inputs = [ "cubestore" ]
[sinks.console_sink_cubestore.encoding]
codec = "json"
[sinks.console_sink_cubestore.cubestore]
levels = [ "CUBE_CLOUD_LOG_EXPORT_CONSOLE_LEVEL-info" ]